### ISSUE TITLE
Piazza code rules

### ISSUE THREAD

**Issue by voytek** [COGS108/Overview#1]
Add section to syllabus noting that Piazza questions with significant homework-related code snippets need to be made private to the staff only, or they will be removed.

**Comment by TomDonoghue** [comment]
This is pretty much already in the syllabus - two sections mention assignment questions, and not to post code that answers questions. 

It could be clarified:
- Specify this applies for asking Qs, as well as answering
- Explicitly point out to use Private Q's to be able to post large code snippets

**Comment by voytek** [comment]
Yeah, just points of clarification, as some students seem to be confused.
